version: '2'

services:
  server:
    build: './server'
    ports:
      - "4343:4343"
  client:
    build: ./client
    volumes:
      - ./client:/home/app/client
      - /home/app/client/node_modules
    ports:
      - "3000:3000"